name: Build and Publish Cluelessly Coder

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  release:
    # Keep the overall job timeout
    timeout-minutes: 60
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18 # Or your preferred Node version

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.5.2 # Or your preferred pnpm version

      - name: Install dependencies
        # This installs @electron/notarize from package.json
        run: pnpm install --no-frozen-lockfile

      - name: Build and Publish (Windows)
        if: matrix.os == 'windows-latest'
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 45
          max_attempts: 3
          command: pnpm run build:win -- --publish always
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEBUG: electron-builder # Optional: for detailed logs

      - name: Build and Publish (Linux)
        if: matrix.os == 'ubuntu-latest'
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 45
          max_attempts: 3
          command: pnpm run build:linux -- --publish always
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEBUG: electron-builder # Optional: for detailed logs
